package enums

// generated by temple from enums.yaml, edit that instead

import "fmt"

type Color int

const (
	ColorRed Color = iota
	ColorGreen
	ColorBlue
)

var colorNames = [...]string{
	"red",
	"green",
	"blue",
}

func (e Color) String() string {
	if e < 0 || int(e) >= len(colorNames) {
		return fmt.Sprintf("Color(%d)", int(e))
	}
	return colorNames[e]
}

func ParseColor(s string) (Color, error) {
	for i, n := range colorNames {
		if n == s {
			return Color(i), nil
		}
	}
	return 0, fmt.Errorf("invalid Color: %q", s)
}

func (e Color) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

func (e *Color) UnmarshalText(b []byte) error {
	v, err := ParseColor(string(b))
	if err != nil {
		return err
	}
	*e = v
	return nil
}

type HttpMethod int

const (
	HttpMethodGet HttpMethod = iota
	HttpMethodPost
	HttpMethodPut
	HttpMethodPatch
	HttpMethodDelete
)

var httpMethodNames = [...]string{
	"get",
	"post",
	"put",
	"patch",
	"delete",
}

func (e HttpMethod) String() string {
	if e < 0 || int(e) >= len(httpMethodNames) {
		return fmt.Sprintf("HttpMethod(%d)", int(e))
	}
	return httpMethodNames[e]
}

func ParseHttpMethod(s string) (HttpMethod, error) {
	for i, n := range httpMethodNames {
		if n == s {
			return HttpMethod(i), nil
		}
	}
	return 0, fmt.Errorf("invalid HttpMethod: %q", s)
}

func (e HttpMethod) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

func (e *HttpMethod) UnmarshalText(b []byte) error {
	v, err := ParseHttpMethod(string(b))
	if err != nil {
		return err
	}
	*e = v
	return nil
}

type LogLevel int

const (
	LogLevelDebug LogLevel = iota
	LogLevelInfo
	LogLevelWarn
	LogLevelError
)

var logLevelNames = [...]string{
	"debug",
	"info",
	"warn",
	"error",
}

func (e LogLevel) String() string {
	if e < 0 || int(e) >= len(logLevelNames) {
		return fmt.Sprintf("LogLevel(%d)", int(e))
	}
	return logLevelNames[e]
}

func ParseLogLevel(s string) (LogLevel, error) {
	for i, n := range logLevelNames {
		if n == s {
			return LogLevel(i), nil
		}
	}
	return 0, fmt.Errorf("invalid LogLevel: %q", s)
}

func (e LogLevel) MarshalText() ([]byte, error) {
	return []byte(e.String()), nil
}

func (e *LogLevel) UnmarshalText(b []byte) error {
	v, err := ParseLogLevel(string(b))
	if err != nil {
		return err
	}
	*e = v
	return nil
}
